install:
  - git submodule update --init --recursive

build_script:
  - cmd: .\build_script.bat

after_build:
  - ps: py .\zip_script.py

artifacts:
  - path: pixi.zip

deploy:
  provider: FTP
  protocol: sftp
  host: www.atarismwc.com
  folder: html/modern_pixi_releases/
  username: pi
  password:
    secure: 5EUQJJ1H2QhydG9QQsaKaQ==